logo = 'img[alt="IT Career Hub"]'
programs = 'Программы'
payment_methods = 'Способы оплаты'
about = 'О нас'
contacts = 'Контакты'
reviews = 'Отзывы'
blog = 'Блог'
language_ru = 'a[href="/ru"]'
language_de = 'de'
callback = '//div[contains(@class, "tn-atom__button-content") and .//span[text()="ОБРАТНЫЙ ЗВОНОК"]]'
consultation_text = '//*[contains(., "Запишитесь на бесплатную карьерную консультацию")]'
