logo = '//img[@alt="IT Career Hub"]'
programs = '//span[text()="Программы"]'
payment_methods = '//span[text()="Способы оплаты"]'
about = '//a[contains(text(), "О нас")]'
contacts = '//a[contains(text(), "Контакты")]'
reviews = '//span[text()="Отзывы"]'
blog = '//span[text()="Блог"]'
language_ru = '//span[text()="ru"]'
language_de = '//a[text()="de"]'
about = '//span[text()="О нас"]'
contacts = '//a[text()="Контакты"]'
callback = '//div[contains(@class, "tn-atom__button-content") and .//span[text()="ОБРАТНЫЙ ЗВОНОК"]]'
consultation_text = '//*[contains(., "Запишитесь на бесплатную карьерную консультацию")]'
